package net.project104.infixparser;

public enum CalculatorError {
    NOT_IMPLEMENTED,
    DIV_BY_ZERO, TOO_BIG, NEGATIVE_SQRT,
    TAN_OUT_DOMAIN, ARCSIN_OUT_RANGE, ARCCOS_OUT_RANGE,
    LOG_OUT_RANGE, WRONG_FACTORIAL,
    NEGATIVE_RADIUS, NEGATIVE_BASE_EXPONENTIATION,
    ROOT_INDEX_ZERO, NEGATIVE_RADICAND, LOG_BASE_ONE,
    SIDE_NEGATIVE, NOT_TRIANGLE, COMPLEX_NUMBER,
    TOO_MANY_ARGS, NOT_ENOUGH_ARGS, LAST_NOT_INT,
    ;
}
